### ISSUE TITLE
Stream Cinema - chybajuce zoznamy a triedenie

### ISSUE THREAD

**Issue by Luky68** [bbaronSVK/metadata.bbaron#1]
Pozdravujem
Pod enigma2 v plugine Stream Cinema a zozname Movies od 0-9 az po Z nejde najst ziadne filmy. Ked zadam vyhladat akekykolvek film z abecedy tak vypisuje len I failed
![img_20170802_225433](https://user-images.githubusercontent.com/15214168/28908688-36d9abb8-7825-11e7-97a1-e6f6f4b7f442.jpg)

**Comment by bbaronSVK** [comment]
Trosku si sa netrafil s repozitarom, ale nevadi.
O tomto viem, zial neviem to nijako otestovat, kedze nemam zariadenie s enigmou2. Neviem to teda nijako opravit. Dal som tam teraz limit na 500 filmov, tak snad to pomoze...
